#=================
# === Automations
#=================
automation:

  #====================================================================
  #=== Master Control switch 
  #===
  #=== This turns on or off,
  #===   All the Irrigation automations.
  #===   All the automations related to Weather used in Irrigation.
  #===
  #===   i.e. all automations with a name beginning with either
  #===        'Irrigation - ' or
  #===        'Irrigation Weather - '
  #===
  #=== Also checks when HA starts.
  #====================================================================
  - alias: Irrigation Master Control Switch
    initial_state: 'on'
    trigger:
      - platform: state
        entity_id: input_boolean.irrigation_master_control_switch

      - platform: homeassistant
        event: start

    action:
      #=== Turn all Irrigation automations on or off
      - service_template: >
          {% if is_state('input_boolean.irrigation_master_control_switch', 'on') %}
            automation.turn_on
          {% else %}
            automation.turn_off
          {% endif %}
        data_template:
          entity_id: >
            {% for item in states['automation'] if item.name.startswith('Irrigation - ') -%}
              {% if not loop.first %},{% endif %}{{ item.entity_id }}
            {%- endfor %}

      #=== Turn all Weather Irrigation automations on or off
      - service_template: >
          {% if is_state('input_boolean.irrigation_master_control_switch', 'on') %}
            automation.turn_on
          {% else %}
            automation.turn_off
          {% endif %}
        data_template:
          entity_id: >
            {% for item in states['automation'] if item.name.startswith('Irrigation Weather - ') -%}
              {% if not loop.first %},{% endif %}{{ item.entity_id }}
            {%- endfor %}
